name: Push Container to Heroku

on:
  push:
    branches:
      - heroku

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: "jirawatk1999@hotmail.com"
          api_key: "jirwatk1999@1234five"
          app_name: "deep-face-api"
          dockerfile: "heroku"
